# docs: https://hub.docker.com/r/sonatype/nexus3
# ports: 8081
version: '3'

services:
  nexus:
    image: sonatype/nexus3
    ports:
      - '8081:8081'
    restart: unless-stopped
    volumes:
      - ./nexus/data:/nexus-data
