# docs: https://hub.docker.com/r/minio/minio
# docs: https://min.io/docs/minio/container/operations/install-deploy-manage/deploy-minio-single-node-single-drive.html#create-and-run-the-container
# source code: https://github.com/minio/minio
# ports: 9001
version: '3'

services:
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=<username>
      - MINIO_ROOT_PASSWORD=<password>
    ports:
      - '9000:9000'
      - '9001:9001'
    restart: unless-stopped
    volumes:
      - ./minio/data:/data
